# Generated by Django 3.1.6 on 2021-02-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Ievadiet dzīvnieka dzimtu (ģenitīva locījumā, daudzskaitlī)', max_length=35, verbose_name='Dzimta')),
            ],
            options={
                'verbose_name': 'Dzimta',
                'verbose_name_plural': 'Dzimtas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(help_text='Ievadiet dzīvnieka pilno latīņu nosaukumu', max_length=100, verbose_name='Latīņu nosaukums')),
                ('latin_name', models.CharField(help_text='Ievadiet dzīvnieka pilno latīņu nosaukumu', max_length=100, verbose_name='Latīņu nosaukums')),
                ('text', models.TextField(help_text='Ievadiet tekstuālu aprakstu par dzīvnieku', verbose_name='Teksts')),
                ('image', models.ImageField(help_text='Augšupielādējiet attēlu ar dzīvnieku', upload_to='photos/%Y/%m/%d/', verbose_name='Bilde')),
                ('family_name', models.ForeignKey(help_text='Izvēlieties dzīvnieka dzimtu', on_delete=django.db.models.deletion.PROTECT, to='animals.family', verbose_name='Dzimta')),
            ],
            options={
                'verbose_name': 'Dzīvnieku',
                'verbose_name_plural': 'Dzīvnieki',
                'ordering': ['-id'],
            },
        ),
    ]
