# Generated by Django 3.1.6 on 2021-02-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animals',
            options={'ordering': ['-id'], 'verbose_name': 'Dzīvnieks', 'verbose_name_plural': 'Dzīvnieki'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['-id'], 'verbose_name': 'Dzimta', 'verbose_name_plural': 'Dzimtas'},
        ),
        migrations.AlterField(
            model_name='animals',
            name='animal_name',
            field=models.CharField(help_text='Ievadiet dzīvnieka nosaukumu', max_length=100, verbose_name='Nosaukums'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='family_name',
            field=models.ForeignKey(help_text='Izvēlieties dzīvnieka dzimtu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.family', verbose_name='Dzimta'),
        ),
    ]
