# Generated by Django 3.1.6 on 2021-02-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20210208_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='family_name',
            field=models.ForeignKey(help_text='Izvēlieties dzīvnieka dzimtu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.family', verbose_name='Dzimta'),
        ),
    ]
