# Generated by Django 3.1.6 on 2021-02-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20210208_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='photos/qr_codes'),
        ),
    ]
