# Generated by Django 3.1.6 on 2021-02-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animals_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='prefix',
            field=models.SlugField(blank=True, help_text='Ievadiet domēna nosaukumu, kas tiks izmantots, kā prefikss priekš QR-koda saites', null=True, verbose_name='Domēns'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='photos/qr_codes', verbose_name='QR-kods'),
        ),
    ]
