# Generated by Django 3.1.6 on 2021-02-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_auto_20210228_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='prefix',
            field=models.URLField(blank=True, help_text='Ievadiet domēna nosaukumu, kas tiks izmantots, kā prefikss priekš QR-koda saites', null=True, verbose_name='Domēns'),
        ),
    ]
